In [27]:
import glob
import os
import pickle

import numpy as np
import pandas as pd

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.utils import shuffle
from string import digits
from tqdm import tqdm

In [3]:
df_2014 = pd.read_csv("../data/tp/eu/de/de_Twitter_2014.csv")

In [94]:
df = pd.read_csv("../data/tp/eu/de/de_Twitter.csv")

In [95]:
len(df)

1090423

In [100]:
df = pd.read_csv("../data/tp/eu/de/de_Twitter/de_Twitter.csv")
len(df)

320832

In [98]:
df = df.preprocessed_text.drop_duplicates().dropna()

In [99]:
df

0         politik europaische union de maiziere kritisie...
1         durchschnittl rentenniveau dt euvergleich haus...
2         soros bleiben drecksack zielen sein europa und...
3         hammer stimmen lieben freiburger ja ua stadt f...
4         tellkamp unterstutzungsrecherchen britisch lin...
                                ...                        
320827    retweeted hansson geheimplan turkei orban eu p...
320828    vorburgerkrieg fluchtlingsheim brandstiftung e...
320829    eustaaten werfen mitverantwortlich fur der aus...
320830    deutschland offenbar eumilliarden fur fluchtli...
320831    genau jahr euebene etlich anderungen asylpolit...
Name: preprocessed_text, Length: 320832, dtype: object

In [76]:
lang = "es"

In [77]:
df_ls = []
for file in glob.glob(f"../data/tp/un/{lang}/{lang}_Twitter*.csv"):
    df_ = pd.read_csv(file)
    df_ls.append(df_)

In [78]:
df= pd.concat(df_ls)

In [79]:
df= df[df["LEN"]>2]

In [80]:
len(df)

1716458

In [81]:
df.to_csv(f"../data/tp/un/{lang}/{lang}_Twitter.csv", index=False)

In [83]:
remove_digits = str.maketrans('', '', digits)

In [82]:
df.preprocessed_text = df.preprocessed_text.apply(lambda x: x.translate(remove_digits))

In [84]:
X = df.preprocessed_text.drop_duplicates().dropna().tolist()

In [85]:
len(X)

203599

In [86]:
countvectorizer = CountVectorizer(ngram_range=(1,2))

In [87]:
X1 = countvectorizer.fit_transform(X) 
features = (countvectorizer.get_feature_names_out())

In [89]:
features.tolist()

['aa',
 'aa guerra',
 'aa informar',
 'aa onu',
 'aa paro',
 'aa politica',
 'aa ps',
 'aa sacar',
 'aa teamsandory',
 'aaa',
 'aaa que',
 'aaaaa',
 'aaaaa plop',
 'aaaaa poootaaaaaa',
 'aaaaa que',
 'aaaaaaaah',
 'aaaaaaaah intocable',
 'aaaaah',
 'aaaaanos',
 'aaaaanos resulta',
 'aaaah',
 'aaaah resumen',
 'aaaayyyy',
 'aaaayyyy cuarto',
 'aaah',
 'aaah acnur',
 'aaah con',
 'aaah nota',
 'aaah pa',
 'aaah pedir',
 'aaah tocar',
 'aaah verdad',
 'aaahhh',
 'aaahhh estrategia',
 'aaahhh resultado',
 'aaahhhh',
 'aaahhhh campo',
 'aaassscccoooo',
 'aaassscccoooo quitar',
 'aacfb',
 'aacfb latinopalestino',
 'aacid',
 'aacid nestor',
 'aacid participar',
 'aahh',
 'aahh noo',
 'aaiun',
 'aaiun ocupar',
 'aajajajjajjaesto',
 'aajajajjajjaesto ser',
 'aal',
 'aal in',
 'aal inmi',
 'aal inmigrante',
 'aal inmigrar',
 'aal luiisx',
 'aal men',
 'aal menar',
 'aal nino',
 'aal themonsterrd',
 'aalgunas',
 'aalgunas amenaza',
 'aalia',
 'aalia espana',
 'aaliaapoyado',
 'aaliaapoyado inform

# applying tfidf

In [90]:
vectorizer = TfidfVectorizer(ngram_range = (1,2))
X2 = vectorizer.fit_transform(X)
scores = (X2.toarray())
print("\n\nScores : \n", scores)



Scores : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [91]:
sums = X2.sum(axis = 0)
data1 = []
for col, term in enumerate(features):
    data1.append( (term, sums[0,col] ))
ranking = pd.DataFrame(data1, columns = ['term','rank'])
words = (ranking.sort_values('rank', ascending = False))
print ("\n\nWords head : \n", words.head(100))



Words head : 
                 term          rank
235319            el  10298.924260
171840            de   6565.607222
638133     refugiado   5564.635423
524860           onu   4916.555161
7072           acnur   3570.300602
...              ...           ...
359412        humano    472.199111
235630    el agencia    471.070954
465076  migracion de    467.225564
194920      denuncia    466.363107
30435         alerta    461.686809

[100 rows x 2 columns]


In [92]:
words = ranking.sort_values('rank', ascending = False)

In [93]:
words

term          rank
235319                el  10298.924260
171840                de   6565.607222
638133         refugiado   5564.635423
524860               onu   4916.555161
7072               acnur   3570.300602
...                  ...           ...
702541      sobre mentar      0.078338
466397  migracion mentar      0.078338
701009     situacion tvn      0.078338
779688        vih mentar      0.078338
261415   encuesta mentar      0.078338

[799404 rows x 2 columns]